# -*- encoding: utf-8 -*-

# import os
# import json

from .. import os, inspect, log_cis, pformat, json, json_util

cwd = os.getcwd()

json_folderpath = cwd + "/app/static/json/"



### + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ###
### NORMALIZATION TAGS / UTILS
### + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ###

def normalization_as_json( var_name, norm_dict, filepath=json_folderpath ) :
	"""
	dumps all norm_dict in a pseudo-json file
	"""

	# locals_function = locals()
	# log_cis.info("... normalization_as_json / locals_function : %s", locals_function )
	# intro_var		= [ k for k,v in locals_function.iteritems() ]
	# log_cis.info("... normalization_as_json / intro_var : %s", intro_var )

	log_cis.info("... normalization_as_json / file : %s.js", var_name )

	full_filepath = filepath + var_name + '.js'
	json_file = open(full_filepath, "w")

	json_file.write( "var " + var_name + " = " )
	# json_file.write('[')
	json_file.write(json.dumps(norm_dict,indent=4, default=json_util.default))
	# json_file.write(',')
	# json_file.write(']')



### + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ###
### NORMALIZATION / CHOICES FOR CHECKBOXES INPUTS
### + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ###

# CHOICES_DOMAINS 	= [
# 	(u"life_env"		, u"Cadre de vie"),
# 	(u"sust_env"		, u"Développement durable"),
# 	(u"eco_dev"			, u"Développement économique"),
# 	(u"habitat"			, u"Habitat"),
# 	(u"inclusion "		, u"Inclusion"),
# 	(u"social_net"		, u"Lien social"),
# 	(u"health_sport"	, u"Santé et sport"),
# 	(u"employment"		, u"Travail"),
# ]

# CHOICES_METHODS 	= [
# 	(u"cooperate"		, u"Coopération"),
# 	(u"evaluate"		, u"Evaluation"),
# 	(u"govern"			, u"Gouvernance"),
# 	(u"philantropy"		, u"Mécénat"),
# 	(u"mediate"			, u"Médiation"),
# 	(u"participate"		, u"Participation"),
# 	(u"research"		, u"Recherche"),
# ]

# CHOICES_PUBLICS 	= [
# 	(u""				, u"Tous publics"),
# 	(u"handicap"		, u"Handicap"),
# 	(u"youth"			, u"Jeunesse"),
# 	(u"senior"			, u"Seniors"),
# ]

# CHOICES_FILTERS_TAGS = [

# 	{ "domains" 	: {	
# 						"fullname"	: u"Domaines",		
# 						"choices"	: CHOICES_DOMAINS ,
# 					} 	
# 	},
# 	# { "geoloc"		: {	
# 	# 					"fullname"	: u"Localisations",	
# 	# 					"choices"	: [] ,
# 	# 				} 				
# 	# },
# 	# { "partners"	: {	"fullname" 	: u"Sourceurs",		
# 	# 					"choices"	: [] , 
# 	# 				}	
# 	# },
# 	{ "publics"		: {	"fullname"	: u"Publics",		
# 						"choices"	: CHOICES_PUBLICS ,
# 					}	
# 	},
# 	{ "methods"		: {	
# 						"fullname"	: u"Méthodes",		
# 						"choices"	: CHOICES_METHODS , 
# 					}	
# 	},

# ]
# CHOICES_FILTERS_PARTNERS = [
# 	{ "partners"	: {	"fullname" 	: u"Sourceurs",		
# 						"choices"	: [] , 
# 					}	
# 	},
# ]
# CHOICES_FILTERS_GEOLOC = [
# 	{ "geoloc"		: {	
# 						"fullname"	: u"Localisations",	
# 						"choices"	: [] ,
# 					} 				
# 	},
# ]
# normalization_as_json( "CHOICES_FILTERS_TAGS", 		CHOICES_FILTERS_TAGS )
# normalization_as_json( "CHOICES_FILTERS_PARTNERS",	CHOICES_FILTERS_PARTNERS )
# normalization_as_json( "CHOICES_FILTERS_GEOLOC", 	CHOICES_FILTERS_GEOLOC )



CHOICES_FILTERS_TAGS = [

	{ 	"name"		: u"domains_",
		"fullname"	: u"Domaines",		
		"choices"	: [
			{"name" : u"life_env"		, "fullname" : u"Cadre de vie"},
			{"name" : u"sust_env"		, "fullname" : u"Développement durable"},
			{"name" : u"eco_dev"		, "fullname" : u"Développement économique"},
			{"name" : u"habitat"		, "fullname" : u"Habitat"},
			{"name" : u"inclusion"		, "fullname" : u"Inclusion"},
			{"name" : u"social_net"		, "fullname" : u"Lien social"},
			{"name" : u"health_sport"	, "fullname" : u"Santé et sport"},
			{"name" : u"employment"		, "fullname" : u"Travail"},
		]
	},
	
	{	"name"		: u"pubics_",
		"fullname"	: u"Publics",		
		"choices"	: [
			# {"name" : u""				, "fullname" : u"Tous publics"},
			{"name" : u"handicap"		, "fullname" : u"Handicap"},
			{"name" : u"youth"			, "fullname" : u"Jeunesse"},
			{"name" : u"senior"			, "fullname" : u"Seniors"}, 
		]
	},
	
	{ 	"name"		: u"methods_",
		"fullname"	: u"Méthodes",		
		"choices"	: [
			{"name" : u"cooperate"		, "fullname" : u"Coopération"},
			{"name" : u"evaluate"		, "fullname" : u"Evaluation"},
			{"name" : u"govern"			, "fullname" : u"Gouvernance"},
			{"name" : u"philantropy"	, "fullname" : u"Mécénat"},
			{"name" : u"mediate"		, "fullname" : u"Médiation"},
			{"name" : u"participate"	, "fullname" : u"Participation"},
			{"name" : u"research"		, "fullname" : u"Recherche"},
		] , 
	},
]
CHOICES_FILTERS_PARTNERS = [

	{	"name"		: u"sources_",
		"fullname" 	: u"Sourceurs",		
		"choices"	: [

			# {"id" : "aaaaaaaaaaaaaaaaaaaaaaaa" , "name" : u"test",				 				"fullname" : u"test"},
			
			{"id" : "5a9da08d0a82868f49cd3816" , "name" : u"AG2R la mondiale",				 	"fullname" : u"AG2R la mondiale"},
			{"id" : "5aa3de630a828651b2ebfe3e" , "name" : u"Apriles", 							"fullname" : u"Apriles"},
			{"id" : "5a9d9fd80a82868f4973d2d3" , "name" : u"Avise", 							"fullname" : u"Avise"},
			{"id" : "5ab3f5fe0a8286585d3a307e" , "name" : u"Bretagne Creative",					"fullname" : u"Bretagne Creative"},
			{"id" : "5aabf8250a8286bf097cec82" , "name" : u"Fondation Daniel et Nina Carasso", 	"fullname" : u"Fondation Daniel et Nina Carasso"},
			{"id" : "5aaff7360a82860b06c94a6d" , "name" : u"Fondation Veolia", 					"fullname" : u"Fondation Veolia"},
			{"id" : "5aaff8aa0a82860b06c94a6e" , "name" : u"Fondation Vinci",				 	"fullname" : u"Fondation Vinci"},
			{"id" : "5aaff93f0a82860b06c94a6f" , "name" : u"MOT", 								"fullname" : u"MOT"},
			{"id" : "5aaffa390a82860b06c94a70" , "name" : u"Semeoz", 							"fullname" : u"Semeoz"},
			{"id" : "5ab410c00a82863566d5fd05" , "name" : u"My Positive Impact",				"fullname" : u"My Positive Impact"},

		] , 
	},
]
CHOICES_FILTERS_GEOLOC = [

	{	"name"		: u"sources_",
		"fullname" 	: u"Sourceurs",		
		"choices"	: [] , 
	},
]
### create ids:

def add_id_key( list_of_dicts ) :
	for filters_list in list_of_dicts : 
		for filter_ in filters_list["choices"] :
			if filter_ != [] :
				filter_["id"] = filters_list["name"] + filter_["name"]
			else :
				filter_["id"] = u""
	return list_of_dicts

CHOICES_FILTERS_TAGS = add_id_key(CHOICES_FILTERS_TAGS)
# CHOICES_FILTERS_PARTNERS = add_id_key(CHOICES_FILTERS_PARTNERS)
CHOICES_FILTERS_GEOLOC = add_id_key(CHOICES_FILTERS_GEOLOC)

normalization_as_json( "CHOICES_FILTERS_TAGS", 		CHOICES_FILTERS_TAGS )
normalization_as_json( "CHOICES_FILTERS_PARTNERS", 	CHOICES_FILTERS_PARTNERS )
normalization_as_json( "CHOICES_FILTERS_GEOLOC", 	CHOICES_FILTERS_GEOLOC )


### + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ###
### NORMALIZATION / VARS
### + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ###


CATEGORIES_CIS_DICT = {
	
	"pubics_" 	: {	
		u"handicap" 	: [ "HAN" ],
		u"youth" 		: [ "JEU" ],
		u"senior" 		: [ "SEN" ],
	},

	"domains_"	: {	
		u"life_env"		: [ "NUM","LOI","SAN","CUL","AME","URB","HAB" ],
		u"sust_env"		: [ "BIO","EAU","CLI","DEC","ENE","AGR" ],
		u"eco_dev"		: [ "ECO","FIN","COM","INS","SER","EMP" ],
		u"habitat"		: [ "URB","HAB","MOB","AME","ENE" ],
		u"inclusion"	: [ "HAB","INS","DRO","CIT","PAR","EDU","MED","MOB","SAN","EMP" ],
		u"social_net"	: [ "DRO","CIT","COH","CUL","SPO","LOI" ],
		u"health_sport"	: [ "SPO","SAN","AGR","HAN","SEN","JEU" ],
		u"employment"	: [ "INS","EMP","FOR","EDU" ],
	},

	"methods_"	: {	
		u"cooperate"	: [ "COO" ] ,
		u"evaluate"		: [ "EVA" ] ,
		u"govern"		: [ "GOU" ] ,
		u"philantropy"	: [ "MEC" ] ,
		u"mediate"		: [ "MED" ] ,
		u"participate"	: [ "PAR" ] ,
		u"research"		: [ "REC" ] ,
	}

}
normalization_as_json( "CATEGORIES_CIS_DICT", CATEGORIES_CIS_DICT )

CATEGORIES_CIS_DICT_FLAT = {}
for categ, metatags in CATEGORIES_CIS_DICT.iteritems() : 
	for k,v in metatags.iteritems() : 
		CATEGORIES_CIS_DICT_FLAT[ categ + k ] = v
normalization_as_json( "CATEGORIES_CIS_DICT_FLAT", CATEGORIES_CIS_DICT_FLAT )



NOMENCLATURE_CIS_DICT = {
	
	"AGR":{"fullname":u"Agriculture","description":u"alimentation, foret"},
	"AME":{"fullname":u"Aménagement","description":u"espaces publics, gestion de l'espace"},
	"AUT":{"fullname":u"Autres","description":u"société civile, Europe, observation, équipements publics"},
	"BIO":{"fullname":u"Biodiversité","description":u"environnement, espaces verts"},
	"CIT":{"fullname":u"Citoyenneté","description":u"citoyenneté, engagement, mobilisation citoyenne"},
	"CLI":{"fullname":u"Climat","description":u"risques naturels"},
	"COH":{"fullname":u"energie","description":u"solidarités, lien social, vivre ensemble, autonomie, isolement"},
	"COM":{"fullname":u"Communication","description":u""},
	"COP":{"fullname":u"Achats","description":u"commande publique, achats durables"},
	"COR":{"fullname":u"Commerce","description":u"commerce équitable"},
	"CUL":{"fullname":u"Culture","description":u"arts, patrimoine"},
	"DEC":{"fullname":u"Déchets","description":u"recyclage, économie circulaire"},
	"EAU":{"fullname":u"Eau","description":u""},
	"ECO":{"fullname":u"Economie","description":u"développement économique, ESS, entreprenariat, monnaie locale, assurance, auto-production "},
	"EDU":{"fullname":u"Education","description":u"orientation, mobilité internationale, enseignement supérieur, éducation populaire"},
	"EMP":{"fullname":u"Emploi","description":u"groupement employeurs"},
	"ENE":{"fullname":u"Energie","description":u""},
	"EVA":{"fullname":u"Evaluation","description":u""},
	"FIN":{"fullname":u"Finances","description":u"finance solidaire, micro crédit, financements européens"},
	"FOR":{"fullname":u"Formation","description":u"apprentissage, enseignement"},
	"GOU":{"fullname":u"Gouvernance","description":u"organisation, élus, RH, RSE"},
	"HAB":{"fullname":u"Habitat","description":u"logement, éco-construction, travaux publics, rénovation"},
	"HAN":{"fullname":u"Handicap","description":u""},
	"INS":{"fullname":u"Insertion","description":u"insertion professionnelle"},
	"JEU":{"fullname":u"Jeunesse","description":u"enfance"},
	"DRO":{"fullname":u"Droits","description":u"justice, accès aux droits, lutte contre discriminations, harcèlement, sécurité, protection, égalité homme femmes, non recours"},
	"LOI":{"fullname":u"Loisirs","description":u"vacances"},
	"MED":{"fullname":u"Médiation","description":u""},
	"MOB":{"fullname":u"Mobilité","description":u"permis de conduire, transports"},
	"NUM":{"fullname":u"Numérique","description":u""},
	"PAR":{"fullname":u"Participation","description":u"démarches participatives, mobilisation locale, participation usagers"},
	"REC":{"fullname":u"Recherche ","description":u""},
	"SAN":{"fullname":u"Santé","description":u""},
	"SEN":{"fullname":u"Seniors","description":u"intergénérationnel"},
	"SER":{"fullname":u"Services","description":u"services à la population, accueil de jour, accompagnement, animation"},
	"SPO":{"fullname":u"Sports","description":u""},
	"TOU":{"fullname":u"Tourisme","description":u""},
	"URB":{"fullname":u"Urbanisme","description":u""},
	"COO":{"fullname":u"Coopération","description":u"coopération, partenariats, réseaux"},
	"MEC":{"fullname":u"Mécénat","description":u"mécénat, mécénat d'entreprises"}
}
normalization_as_json( "NOMENCLATURE_CIS_DICT", NOMENCLATURE_CIS_DICT )

NOMENCLATURE_CIS_LIST = [ {"code" : k , "fullname" : v["fullname"], "description" : v["description"] } for k,v in NOMENCLATURE_CIS_DICT.iteritems() ]


### TEMPORARY SOLUTION <-- from https://docs.google.com/spreadsheets/d/1c5m5sxza2ehtBPB7mCc8GWKG21pxTVPSuIy0xQ6mYSo/edit#gid=694276620 
NORMALIZATION_TAGS_SOURCES_CIS = [

	{"name":u"Energie","codes":["ENE"],"from":u"ADEME innovation sociale"},
	{"name":u"Alimentation","codes":["AGR"],"from":u"ADEME innovation sociale"},
	{"name":u"Partage","codes":["AUT"],"from":u"ADEME innovation sociale"},
	{"name":u"Autonomie","codes":["SEN","HAN","COH"],"from":u"ODAS - APRILES"},
	{"name":u"Insertion","codes":["INS","FOR","COH"],"from":u"ODAS - APRILES"},
	{"name":u"Enfance / Famille","codes":["JEU","EDU","COH"],"from":u"ODAS - APRILES"},
	{"name":u"Vie des territoires","codes":["COO","PAR","COH"],"from":u"ODAS - APRILES"},
	{"name":u"Santé","codes":["SAN","SER","COH"],"from":u"ODAS - APRILES"},
	{"name":u"identité","codes":["AUT"],"from":u"Atlaas - villes internet"},
	{"name":u"vie associative","codes":["AUT"],"from":u"Atlaas - villes internet"},
	{"name":u"services publics","codes":["AUT"],"from":u"Atlaas - villes internet"},
	{"name":u"démocratie locale","codes":["GOU","PAR","COO"],"from":u"Atlaas - villes internet"},
	{"name":u"vie quotidienne","codes":["AUT"],"from":u"Atlaas - villes internet"},
	{"name":u"cohésion sociale","codes":["COH"],"from":u"Atlaas - villes internet"},
	{"name":u"solidarités","codes":["COH"],"from":u"Atlaas - villes internet"},
	{"name":u"territoire durable","codes":["GOU","AME"],"from":u"Atlaas - villes internet"},
	{"name":u"éducation","codes":["EDU"],"from":u"Atlaas - villes internet"},
	{"name":u"médiation","codes":["MED"],"from":u"Atlaas - villes internet"},
	{"name":u"coopération","codes":["GOU","COO"],"from":u"Atlaas - villes internet"},
	{"name":u"culture et patrimoine","codes":["CUL"],"from":u"Atlaas - villes internet"},
	{"name":u"emploi","codes":["EMP"],"from":u"Atlaas - villes internet"},
	{"name":u"innovation","codes":["AUT"],"from":u"Atlaas - villes internet"},
	{"name":u"développement économique ","codes":["ECO"],"from":u"Atlaas - villes internet"},
	{"name":u"attractivité","codes":["ECO"],"from":u"Atlaas - villes internet"},
	{"name":u"Alimentation","codes":["AGR"],"from":u"Avise"},
	{"name":u"Commerce équitable","codes":["COR"],"from":u"Avise"},
	{"name":u"Développement durable","codes":["BIO","ECO","COH"],"from":u"Avise"},
	{"name":u"Économie circulaire","codes":["ECO"],"from":u"Avise"},
	{"name":u"Égalité femmes hommes","codes":["DRO"],"from":u"Avise"},
	{"name":u"Emploi","codes":["EMP"],"from":u"Avise"},
	{"name":u"Entrepreneuriat social","codes":["ECO"],"from":u"Avise"},
	{"name":u"Environnement","codes":["BIO"],"from":u"Avise"},
	{"name":u"Evaluation de l'impact social","codes":["EVA"],"from":u"Avise"},
	{"name":u"Finance solidaire","codes":["FIN"],"from":u"Avise"},
	{"name":u"Groupement d'employeurs","codes":["EMP"],"from":u"Avise"},
	{"name":u"Habitat","codes":["HAB"],"from":u"Avise"},
	{"name":u"Handicap","codes":["HAN"],"from":u"Avise"},
	{"name":u"Innovation sociale","codes":["GOU","AUT"],"from":u"Avise"},
	{"name":u"Insertion par l’activité économique","codes":["INS"],"from":u"Avise"},
	{"name":u"Jeunesse","codes":["JEU"],"from":u"Avise"},
	{"name":u"Lien social","codes":["COH"],"from":u"Avise"},
	{"name":u"Mécénat","codes":["MEC"],"from":u"Avise"},
	{"name":u"Mobilisation citoyenne","codes":["CIT"],"from":u"Avise"},
	{"name":u"Mobilité","codes":["MOB"],"from":u"Avise"},
	{"name":u"Numérique","codes":["NUM"],"from":u"Avise"},
	{"name":u"Partenariats associations entreprises","codes":["GOU","COO"],"from":u"Avise"},
	{"name":u"Quartiers prioritaires","codes":["COH"],"from":u"Avise"},
	{"name":u"Silver économie","codes":["SEN"],"from":u"Avise"},
	{"name":u"Accompagnement vers l’emploi coaching tri textile","codes":["EMP"],"from":u"Avise"},
	{"name":u"Action sanitaire et sociale","codes":["SAN","COH"],"from":u"Avise"},
	{"name":u"Agriculture","codes":["AGR"],"from":u"Avise"},
	{"name":u"Agriculture biologique","codes":["AGR"],"from":u"Avise"},
	{"name":u"Agriculture tourisme et aménagement du territoire","codes":["AGR","TOU","AME"],"from":u"Avise"},
	{"name":u"Agro-alimentaire","codes":["AGR"],"from":u"Avise"},
	{"name":u"Agroécologie et permaculture","codes":["AGR"],"from":u"Avise"},
	{"name":u"Aide alimentaire","codes":["SAN"],"from":u"Avise"},
	{"name":u"Alimentation","codes":["AGR"],"from":u"Avise"},
	{"name":u"Alimentation solidaire","codes":["AGR","COH"],"from":u"Avise"},
	{"name":u"Animation urbanisme expérimentation","codes":["AME","AUT"],"from":u"Avise"},
	{"name":u"Archivage papier et numérique GED","codes":["NUM"],"from":u"Avise"},
	{"name":u"Boulangerie","codes":["AGR"],"from":u"Avise"},
	{"name":u"Boulangerie artisanale","codes":["AGR","COM"],"from":u"Avise"},
	{"name":u"Café associatif","codes":["COM"],"from":u"Avise"},
	{"name":u"Collecte tri réparation vente d’occasion","codes":["DEC","ECO"],"from":u"Avise"},
	{"name":u"Commerce multiservice","codes":["COM","ECO"],"from":u"Avise"},
	{"name":u"Commerce équitable (distribution de produits)","codes":["COM","COH"],"from":u"Avise"},
	{"name":u"Commercialisation de produits agricoles en circuits courts","codes":["COM"],"from":u"Avise"},
	{"name":u"Conciergerie","codes":["SER"],"from":u"Avise"},
	{"name":u"Conciergerie d’entreprises","codes":["SER","ECO"],"from":u"Avise"},
	{"name":u"Culture","codes":["CUL"],"from":u"Avise"},
	{"name":u"Distribution de produits biologiques et écologiques","codes":["ECO","BIO"],"from":u"Avise"},
	{"name":u"Eco-construction","codes":["HAB","CLI"],"from":u"Avise"},
	{"name":u"Education au développement durable","codes":["EDU","CLI","BIO"],"from":u"Avise"},
	{"name":u"Emploi insertion","codes":["EMP","INS"],"from":u"Avise"},
	{"name":u"Environnement et déchets","codes":["BIO","DEC"],"from":u"Avise"},
	{"name":u"Enérgie","codes":["ENE"],"from":u"Avise"},
	{"name":u"Filière brassicole (agriculture)","codes":["AGR"],"from":u"Avise"},
	{"name":u"Finance","codes":["FIN"],"from":u"Avise"},
	{"name":u"Gestion d'équipement informatique","codes":["NUM"],"from":u"Avise"},
	{"name":u"Gestion des déchets","codes":["DEC"],"from":u"Avise"},
	{"name":u"Habitat (bailleur social)","codes":["HAB"],"from":u"Avise"},
	{"name":u"Habitat social","codes":["HAB","COH"],"from":u"Avise"},
	{"name":u"Informatique","codes":["NUM"],"from":u"Avise"},
	{"name":u"Insertion","codes":["INS"],"from":u"Avise"},
	{"name":u"Insertion par l’activité économique recyclage et vente de vêtements","codes":["INS","ECO"],"from":u"Avise"},
	{"name":u"Insertion sociale","codes":["INS"],"from":u"Avise"},
	{"name":u"Logement","codes":["HAB"],"from":u"Avise"},
	{"name":u"Lutte contre le gaspillage alimentaire","codes":["AGR","DEC"],"from":u"Avise"},
	{"name":u"Maraîchage scierie éco-construction","codes":["AGR","HAB"],"from":u"Avise"},
	{"name":u"Microfinance","codes":["FIN"],"from":u"Avise"},
	{"name":u"Mobilité","codes":["MOB"],"from":u"Avise"},
	{"name":u"Mécénat de compétences","codes":["MEC"],"from":u"Avise"},
	{"name":u"Médiation sociale","codes":["COH"],"from":u"Avise"},
	{"name":u"NTIC personnes âgées","codes":["NUM","SEN"],"from":u"Avise"},
	{"name":u"Numérique","codes":["NUM"],"from":u"Avise"},
	{"name":u"Numérique et inclusion sociale","codes":["NUM","COH"],"from":u"Avise"},
	{"name":u"Numérique et multimédia","codes":["NUM"],"from":u"Avise"},
	{"name":u"PA/PH","codes":["SER"],"from":u"Avise"},
	{"name":u"Paysagisme","codes":["AME"],"from":u"Avise"},
	{"name":u"Petite enfance","codes":["JEU"],"from":u"Avise"},
	{"name":u"Petite enfance jeunesse","codes":["JEU"],"from":u"Avise"},
	{"name":u"Promotion des arts des techniques et des professions liés à la Production et à l’utilisation de l’ocre et des matériaux de la couleur.","codes":["CUL"],"from":u"Avise"},
	{"name":u"Recyclage","codes":["DEC"],"from":u"Avise"},
	{"name":u"Recyclage des encombrants","codes":["DEC"],"from":u"Avise"},
	{"name":u"Restauration","codes":["AGR"],"from":u"Avise"},
	{"name":u"Robotique et santé","codes":["SAN","NUM"],"from":u"Avise"},
	{"name":u"Réinsertion par la culture et le tourisme","codes":["CUL"],"from":u"Avise"},
	{"name":u"Rénovation et location de logements sociaux","codes":["HAB","COH"],"from":u"Avise"},
	{"name":u"Réparation et recyclage de vélos","codes":["DEC"],"from":u"Avise"},
	{"name":u"Santé","codes":["SAN"],"from":u"Avise"},
	{"name":u"Santé et action sociale","codes":["SAN","COH"],"from":u"Avise"},
	{"name":u"Sciences citoyennes et technologies participatives","codes":["CIT","PAR","REC"],"from":u"Avise"},
	{"name":u"Second-œuvre bâtiment éco-construction","codes":["HAB","CLI"],"from":u"Avise"},
	{"name":u"Sensibilisation expérimentation et animation socio-culturelle","codes":["PAR"],"from":u"Avise"},
	{"name":u"Services à la personne","codes":["SER"],"from":u"Avise"},
	{"name":u"Silver économie","codes":["SEN","ECO"],"from":u"Avise"},
	{"name":u"Solidarité","codes":["COH"],"from":u"Avise"},
	{"name":u"Technologie innovante revalorisation de produits invendables ou invendus","codes":["DEC","NUM"],"from":u"Avise"},
	{"name":u"Technologies de l’information et de la communication","codes":["NUM"],"from":u"Avise"},
	{"name":u"Transport","codes":["MOB"],"from":u"Avise"},
	{"name":u"Transport intra-urbain de marchandises insertion professionnelle","codes":["MOB"],"from":u"Avise"},
	{"name":u"Upcycling","codes":["EDU","AUT"],"from":u"Avise"},
	{"name":u"Vie étudiante","codes":["JEU","EDU"],"from":u"Avise"},
	{"name":u"coworking","codes":["EMP"],"from":u"Avise"},
	{"name":u"Écoconception","codes":["ECO","BIO"],"from":u"Avise"},
	{"name":u"Politiques publiques","codes":["CIT","GOU"],"from":u"Bretagne Créative"},
	{"name":u"Professionnalisation / formation","codes":["AUT"],"from":u"Bretagne Créative"},
	{"name":u"PTCE","codes":["CUL"],"from":u"Bretagne Créative"},
	{"name":u"Quartiers prioritaires","codes":["AUT"],"from":u"Bretagne Créative"},
	{"name":u"Reprise d'entreprise","codes":["BIO"],"from":u"Bretagne Créative"},
	{"name":u"Ressources humaines","codes":["GOU"],"from":u"Bretagne Créative"},
	{"name":u"RSE","codes":["GOU"],"from":u"Bretagne Créative"},
	{"name":u"Silver économie","codes":["SAN","SEN"],"from":u"Bretagne Créative"},
	{"name":u"Social","codes":["COH"],"from":u"Bretagne Créative"},
	{"name":u"Solidarité","codes":["COH"],"from":u"Bretagne Créative"},
	{"name":u"Organisation sociale des territoires et des villes","codes":["GOU"],"from":u"Citego"},
	{"name":u"Capital humain des territoires","codes":["CUL","AUT"],"from":u"Citego"},
	{"name":u"Inégalités sociales et territoire","codes":["COH","DRO"],"from":u"Citego"},
	{"name":u"conflits sociaux et luttes sociales dans un territoire","codes":["COH"],"from":u"Citego"},
	{"name":u"Modes de vie","codes":["CIT","AUT"],"from":u"Citego"},
	{"name":u"Identité territoriale","codes":["AUT"],"from":u"Citego"},
	{"name":u"Structure économique des territoires","codes":["ECO"],"from":u"Citego"},
	{"name":u"Structures commerciales","codes":["COM"],"from":u"Citego"},
	{"name":u"Structures foncières, propriété foncière et marchés fonciers","codes":["ECO"],"from":u"Citego"},
	{"name":u"Emploi et marché de l'emploi","codes":["EMP"],"from":u"Citego"},
	{"name":u"Agriculture et production agricole","codes":["AGR"],"from":u"Citego"},
	{"name":u"Actvités économiques","codes":["ECO"],"from":u"Citego"},
	{"name":u"Marché foncier","codes":["ECO"],"from":u"Citego"},
	{"name":u"Écosystème des territoires","codes":["GOU"],"from":u"Citego"},
	{"name":u"Empreinte écologique des territoires","codes":["BIO","EAU","DEC"],"from":u"Citego"},
	{"name":u"ressources naturelles, capital naturel et territoire","codes":["BIO","EAU","DEC"],"from":u"Citego"},
	{"name":u"air et territoire","codes":["BIO"],"from":u"Citego"},
	{"name":u"Sols et territoire","codes":["BIO"],"from":u"Citego"},
	{"name":u"Biodiversité et territoire","codes":["BIO"],"from":u"Citego"},
	{"name":u"Climat et territoire","codes":["CLI"],"from":u"Citego"},
	{"name":u"Eau et territoire","codes":["BIO"],"from":u"Citego"},
	{"name":u"Patrimoine naturel","codes":["BIO"],"from":u"Citego"},
	{"name":u"Équipements collectifs","codes":["AUT"],"from":u"Citego"},
	{"name":u"Habitat et marché du logement","codes":["HAB"],"from":u"Citego"},
	{"name":u"Réseaux urbains et infrastructures","codes":["URB"],"from":u"Citego"},
	{"name":u"Culture, diversité culturelle et territoires","codes":["CUL"],"from":u"Citego"},
	{"name":u"capital immatériel des territoires","codes":["CUL"],"from":u"Citego"},
	{"name":u"capacités d'adaptation, résilience","codes":["GOU"],"from":u"Citego"},
	{"name":u"patrimoine historique des territoires","codes":["CUL"],"from":u"Citego"},
	{"name":u"patrimoine culturel","codes":["CUL"],"from":u"Citego"},
	{"name":u"Patrimoine bâti","codes":["HAB","CUL"],"from":u"Citego"},
	{"name":u"Espace public","codes":["URB"],"from":u"Citego"},
	{"name":u"paysages","codes":["BIO"],"from":u"Citego"},
	{"name":u"Formes urbaines","codes":["URB"],"from":u"Citego"},
	{"name":u"Centralité","codes":["AUT"],"from":u"Citego"},
	{"name":u"Flux et réseaux de transports des personnes (déplacements internes)","codes":["MOB"],"from":u"Citego"},
	{"name":u"flux d'argent (circulation interne )","codes":["ECO"],"from":u"Citego"},
	{"name":u"Flux de matière (circulation interne et échanges avec l'extérieur) et réseaux de transports","codes":["MOB"],"from":u"Citego"},
	{"name":u"flux d’information et réseaux de télécommunication (circulation interne et échanges avec l’extérieur)","codes":["COM"],"from":u"Citego"},
	{"name":u"flux d’énergie et territoires","codes":["ENE"],"from":u"Citego"},
	{"name":u"Systèmes démocratiques","codes":["GOU"],"from":u"Citego"},
	{"name":u"Systèmes politiques","codes":["GOU"],"from":u"Citego"},
	{"name":u"Territoires dans l'économie mondiale, territoires et filières mondiales de production","codes":["AUT"],"from":u"Citego"},
	{"name":u"Relations entre territoires: interdépendance, dépendance, concurrence","codes":["COO"],"from":u"Citego"},
	{"name":u"Atouts économiques des territoires","codes":["ECO"],"from":u"Citego"},
	{"name":u"flux de personnes (échanges avec l'extérieur)","codes":["MOB"],"from":u"Citego"},
	{"name":u"Flux d'argent (échanges avec l'extérieur)","codes":["ECO"],"from":u"Citego"},
	{"name":u"flux de matières (échanges avec l’extérieur)","codes":["ECO"],"from":u"Citego"},
	{"name":u"flux d'information (échanges avec l'extérieur)","codes":["COM"],"from":u"Citego"},
	{"name":u"Types de territoires selon leurs caractéristiques géographiques, naturelles et morphologiques","codes":["AUT"],"from":u"Citego"},
	{"name":u"Types de villes","codes":["AUT"],"from":u"Citego"},
	{"name":u"Échelles territoriales","codes":["AUT"],"from":u"Citego"},
	{"name":u"Dynamiques de la société","codes":["AUT"],"from":u"Citego"},
	{"name":u"Transition vers des sociétés durables","codes":["AUT"],"from":u"Citego"},
	{"name":u"Dynamiques de l'économie","codes":["ECO"],"from":u"Citego"},
	{"name":u"Dynamiques de l'écosystème","codes":["AUT"],"from":u"Citego"},
	{"name":u"Dynamiques culturelles (cohabitation des cultures, héritage culturel, évolutions culturelles)","codes":["CUL"],"from":u"Citego"},
	{"name":u"Dynamique des idées et des systèmes de pensée","codes":["AUT"],"from":u"Citego"},
	{"name":u"Dynamiques spatiales","codes":["AUT"],"from":u"Citego"},
	{"name":u"Dynamiques de développement et d'évolution des territoires","codes":["AUT"],"from":u"Citego"},
	{"name":u"Dynamiques des systèmes techniques","codes":["AUT"],"from":u"Citego"},
	{"name":u"Dynamiques de la gouvernance","codes":["GOU"],"from":u"Citego"},
	{"name":u"Mouvements migratoires, flux migratoires et territoires","codes":["MOB"],"from":u"Citego"},
	{"name":u"Acteurs de la société","codes":["AUT"],"from":u"Citego"},
	{"name":u"Acteurs de l'économie","codes":["ECO"],"from":u"Citego"},
	{"name":u"Acteurs de la gestion des écosystèmes territoriaux","codes":["AUT"],"from":u"Citego"},
	{"name":u"Acteurs de la gestion des infrastructures et des équipements","codes":["AUT"],"from":u"Citego"},
	{"name":u"Acteurs de la culture, de la connaissance et de l'information","codes":["CUL","COM"],"from":u"Citego"},
	{"name":u"Acteurs de l'organisation de l'espace, de l'aménagement","codes":["URB"],"from":u"Citego"},
	{"name":u"Acteurs de la gestion des flux","codes":["AUT"],"from":u"Citego"},
	{"name":u"Acteurs de la gouvernance","codes":["GOU"],"from":u"Citego"},
	{"name":u"Acteurs de la mondialisation","codes":["AUT"],"from":u"Citego"},
	{"name":u"Société","codes":["AUT"],"from":u"Citego"},
	{"name":u"Développement économique","codes":["ECO"],"from":u"Citego"},
	{"name":u"Pensée et modèles de développement","codes":["ECO"],"from":u"Citego"},
	{"name":u"Gestion des écosystèmes territoriaux","codes":["GOU"],"from":u"Citego"},
	{"name":u"Gestion des ressources naturelles","codes":["BIO","EAU","DEC"],"from":u"Citego"},
	{"name":u"Recherche et production de connaissances","codes":["REC"],"from":u"Citego"},
	{"name":u"Arts et culture","codes":["CUL"],"from":u"Citego"},
	{"name":u"Éducation et diffusion de connaissances","codes":["EDU","FOR"],"from":u"Citego"},
	{"name":u"Aménagement du territoire","codes":["URB"],"from":u"Citego"},
	{"name":u"Gestion des flux","codes":["AUT"],"from":u"Citego"},
	{"name":u"Relations du territoire avec l'extérieur","codes":["GOU","COO"],"from":u"Citego"},
	{"name":u"Organisation politique et institutionnelle","codes":["GOU"],"from":u"Citego"},
	{"name":u"Élaboration et mise en œuvre des droits et des règles","codes":["DRO","AUT"],"from":u"Citego"},
	{"name":u"Organisation et délivrance de services d'intérêt général","codes":["AUT"],"from":u"Citego"},
	{"name":u"Fiscalité et financement","codes":["FIN"],"from":u"Citego"},
	{"name":u"Coordination des acteurs","codes":["GOU","COO"],"from":u"Citego"},
	{"name":u"Établissement de préférences collectives","codes":["AUT"],"from":u"Citego"},
	{"name":u"Outils de l’action","codes":["AUT"],"from":u"Citego"},
	{"name":u"Démocratie et citoyenneté","codes":["CIT"],"from":u"Citego"},
	{"name":u"Légitimité de la gouvernance","codes":["GOU"],"from":u"Citego"},
	{"name":u"Pertinence des dispositifs de gouvernance","codes":["GOU"],"from":u"Citego"},
	{"name":u"Co-production du bien public","codes":["GOU"],"from":u"Citego"},
	{"name":u"Articulation des échelles de gouvernance","codes":["GOU","COO"],"from":u"Citego"},
	{"name":u"Oasis de vie / Habitat participatif","codes":["HAB"],"from":u"Colibris / carte des oasis"},
	{"name":u"Oasis ressources","codes":["AUT"],"from":u"Colibris / carte des oasis"},
	{"name":u"Autre","codes":["HAB"],"from":u"Colibris / carte des oasis"},
	{"name":u"Emploi & Citoyenneté","codes":["EMP","CIT"],"from":u"COORACE - Nos territoires ont de l'avenir"},
	{"name":u"Mobilisation locale & Coopérations innovantes ","codes":["GOU","PAR"],"from":u"COORACE - Nos territoires ont de l'avenir"},
	{"name":u"Environnement & Nouvelle économie","codes":["ECO","BIO"],"from":u"COORACE - Nos territoires ont de l'avenir"},
	{"name":u"Alimentation durable","codes":["AGR","DEC"],"from":u"Fondation Daniel et Nina Carasso"},
	{"name":u"Art citoyen","codes":["CUL","CIT"],"from":u"Fondation Daniel et Nina Carasso"},
	{"name":u"Alternance","codes":["FOR","EMP","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"ASE - PJJ - Justice  ","codes":["DRO","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Culture","codes":["CUL","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Décrochage scolaire","codes":["EDU","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Insertion professionnelle","codes":["INS","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Logement","codes":["HAB","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Lutte contre les discriminations  ","codes":["DRO","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Mobilité internationale ","codes":["EDU","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Orientation","codes":["EDU","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Permis de conduire","codes":["MOB","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Santé  ","codes":["SAN","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Engagement des jeunes","codes":["CIT","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Décrochage universitaire ","codes":["EDU","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Livret de compétences ","codes":["EDU","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Réussite scolaire ","codes":["EDU","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Revenu contractualisé d’autonomie","codes":["EMP","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Education populaire","codes":["EDU","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Lutte contre le harcèlement à l'école","codes":["DRO","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Numérique","codes":["NUM","JEU"],"from":u"Fonds d'expérimentation pour la jeunesse"},
	{"name":u"Espace agricole","codes":["AGR"],"from":u"Fondation RTE"},
	{"name":u"Employabilité","codes":["EMP","INS"],"from":u"Fondation RTE"},
	{"name":u"Patrimoine rural","codes":["CUL"],"from":u"Fondation RTE"},
	{"name":u"Échanges ville & campagne","codes":["GOU","COO"],"from":u"Fondation RTE"},
	{"name":u"Habitat","codes":["HAB"],"from":u"Fondation RTE"},
	{"name":u"Égalité territoriale","codes":["AUT"],"from":u"Fondation RTE"},
	{"name":u"Urgence & Développement","codes":["COH"],"from":u"Fondation Veolia"},
	{"name":u"Emploi & Lien social","codes":["EMP","COH"],"from":u"Fondation Veolia"},
	{"name":u"Environnement & Biodiversité","codes":["BIO"],"from":u"Fondation Veolia"},
	{"name":u"Mécénat de compétences","codes":["MEC"],"from":u"Fondation Veolia"},
	{"name":u"Accès à l'emploi","codes":["EMP"],"from":u"Fondation Vinci pour la cité"},
	{"name":u"Mobilité solidaire","codes":["MOB"],"from":u"Fondation Vinci pour la cité"},
	{"name":u"Quartiers prioritaires et lien social","codes":["COH"],"from":u"Fondation Vinci pour la cité"},
	{"name":u"Insertion par le logement","codes":["HAB"],"from":u"Fondation Vinci pour la cité"},
	{"name":u"Patrimoine & culture","codes":["CUL"],"from":u"FNCE"},
	{"name":u"Patrimoine & culture","codes":["CUL"],"from":u"FNCE"},
	{"name":u"Solidarité","codes":["COH","INS","HAN","EDU"],"from":u"FNCE"},
	{"name":u"Solidarité","codes":["COH","INS","HAN","EDU"],"from":u"FNCE"},
	{"name":u"Solidarité","codes":["COH","INS","HAN"],"from":u"FNCE"},
	{"name":u"Solidarité","codes":["COH","INS","HAN"],"from":u"FNCE"},
	{"name":u"Solidarité","codes":["COH","INS","HAN","EDU","HAB","AGR"],"from":u"FNCE"},
	{"name":u"Education financière","codes":["EDU","FIN"],"from":u"FNCE"},
	{"name":u"Soutien à la création d'entreprise","codes":["EMP"],"from":u"FNCE"},
	{"name":u"Autres","codes":["AUT","SPO"],"from":u"FNCE"},
	{"name":u"Autres","codes":["AUT","EDU","REC"],"from":u"FNCE"},
	{"name":u"Autres","codes":["AUT","BIO","EAU","DEC"],"from":u"FNCE"},
	{"name":u"Agriculture ","codes":["AGR"],"from":u"Le Labo de l'ESS"},
	{"name":u"Alimentation","codes":["AGR"],"from":u"Le Labo de l'ESS"},
	{"name":u"Circuits courts","codes":["ECO"],"from":u"Le Labo de l'ESS"},
	{"name":u"Commerce équitable","codes":["COR"],"from":u"Le Labo de l'ESS"},
	{"name":u"Communs","codes":["GOU","COO"],"from":u"Le Labo de l'ESS"},
	{"name":u"Culture","codes":["CUL"],"from":u"Le Labo de l'ESS"},
	{"name":u"Démocratie","codes":["GOU","PAR"],"from":u"Le Labo de l'ESS"},
	{"name":u"Développement durable","codes":["BIO","ECO","COH"],"from":u"Le Labo de l'ESS"},
	{"name":u"Eco-construction","codes":["HAB"],"from":u"Le Labo de l'ESS"},
	{"name":u"Economie circulaire","codes":["ECO","DEC"],"from":u"Le Labo de l'ESS"},
	{"name":u"Economie collaborative","codes":["ECO"],"from":u"Le Labo de l'ESS"},
	{"name":u"Education","codes":["EDU"],"from":u"Le Labo de l'ESS"},
	{"name":u"Emploi ","codes":["EMP"],"from":u"Le Labo de l'ESS"},
	{"name":u"Europe","codes":["AUT"],"from":u"Le Labo de l'ESS"},
	{"name":u"Evaluation","codes":["EVA"],"from":u"Le Labo de l'ESS"},
	{"name":u"Finance solidaire","codes":["FIN"],"from":u"Le Labo de l'ESS"},
	{"name":u"Financement","codes":["FIN"],"from":u"Le Labo de l'ESS"},
	{"name":u"Insertion","codes":["INS"],"from":u"Le Labo de l'ESS"},
	{"name":u"Jeunes","codes":["JEU"],"from":u"Le Labo de l'ESS"},
	{"name":u"Logement","codes":["HAB"],"from":u"Le Labo de l'ESS"},
	{"name":u"Mécénat","codes":["MEC"],"from":u"Le Labo de l'ESS"},
	{"name":u"Mobilité","codes":["MOB"],"from":u"Le Labo de l'ESS"},
	{"name":u"Monnaie locale","codes":["ECO"],"from":u"Le Labo de l'ESS"},
	{"name":u"Numérique","codes":["NUM"],"from":u"Le Labo de l'ESS"},
	{"name":u"PTCE","codes":["GOU","ECO"],"from":u"Le Labo de l'ESS"},
	{"name":u"Responsabilité sociale des entreprises (RSE)","codes":["GOU"],"from":u"Le Labo de l'ESS"},
	{"name":u"Rural","codes":["AUT"],"from":u"Le Labo de l'ESS"},
	{"name":u"Santé","codes":["SAN"],"from":u"Le Labo de l'ESS"},
	{"name":u"Seniors","codes":["SEN"],"from":u"Le Labo de l'ESS"},
	{"name":u"Services à la personne","codes":["SER"],"from":u"Le Labo de l'ESS"},
	{"name":u"Solidarité","codes":["COH"],"from":u"Le Labo de l'ESS"},
	{"name":u"Tiers-lieux","codes":["HAB","AUT"],"from":u"Le Labo de l'ESS"},
	{"name":u"Tourisme","codes":["TOU"],"from":u"Le Labo de l'ESS"},
	{"name":u"Transition énergétique","codes":["ENE"],"from":u"Le Labo de l'ESS"},
	{"name":u"Changement climatique, gestion et prévention des risques","codes":["CLI"],"from":u"MOT"},
	{"name":u"Culture","codes":["CUL"],"from":u"MOT"},
	{"name":u"Culture et société civile","codes":["CUL"],"from":u"MOT"},
	{"name":u"Développement économique transfrontalier","codes":["ECO"],"from":u"MOT"},
	{"name":u"Education, formation, langues","codes":["EDU","FOR"],"from":u"MOT"},
	{"name":u"Emploi","codes":["EMP"],"from":u"MOT"},
	{"name":u"Energies","codes":["ENE"],"from":u"MOT"},
	{"name":u"Environnement, ressources, déchets","codes":["BIO","DEC"],"from":u"MOT"},
	{"name":u"Inclusion sociale","codes":["COH"],"from":u"MOT"},
	{"name":u"Recherche et innovation","codes":["REC"],"from":u"MOT"},
	{"name":u"Santé","codes":["SAN"],"from":u"MOT"},
	{"name":u"Sécurité, police","codes":["DRO"],"from":u"MOT"},
	{"name":u"Société civile","codes":["AUT"],"from":u"MOT"},
	{"name":u"Sport","codes":["SPO"],"from":u"MOT"},
	{"name":u"TIC, télécommunications et services postaux","codes":["COM","NUM"],"from":u"MOT"},
	{"name":u"Tourisme","codes":["TOU"],"from":u"MOT"},
	{"name":u"Transports","codes":["MOB"],"from":u"MOT"},
	{"name":u"Alimentation","codes":["AGR"],"from":u"My Positive Impact (Fondation Nicolas Hulot)"},
	{"name":u"Citoyenneté","codes":["CIT"],"from":u"My Positive Impact (Fondation Nicolas Hulot)"},
	{"name":u"Déchets","codes":["DEC"],"from":u"My Positive Impact (Fondation Nicolas Hulot)"},
	{"name":u"Eau et biodiversité","codes":["BIO","EAU"],"from":u"My Positive Impact (Fondation Nicolas Hulot)"},
	{"name":u"Énergie","codes":["ENE"],"from":u"My Positive Impact (Fondation Nicolas Hulot)"},
	{"name":u"Habitat et cadre de vie","codes":["HAB"],"from":u"My Positive Impact (Fondation Nicolas Hulot)"},
	{"name":u"Mobilité","codes":["MOB"],"from":u"My Positive Impact (Fondation Nicolas Hulot)"},
	{"name":u"Agriculture","codes":["AGR"],"from":u"Réseau rural "},
	{"name":u"Coopération, recherche et innovation","codes":["GOU","REC","COO"],"from":u"Réseau rural "},
	{"name":u"Environnement","codes":["BIO"],"from":u"Réseau rural "},
	{"name":u"Economie","codes":["ECO"],"from":u"Réseau rural "},
	{"name":u"Alimentation","codes":["AGR"],"from":u"Réseau rural "},
	{"name":u"Accueil et services à la population et aux entreprises","codes":["COH","ECO","SER"],"from":u"Réseau rural "},
	{"name":u"Forêt","codes":["AGR"],"from":u"Réseau rural "},
	{"name":u"Territoire et gestion de l'espace","codes":["AME"],"from":u"Réseau rural "},
	{"name":u"alimentation durable","codes":["AGR"],"from":u"RTES"},
	{"name":u"communs","codes":["GOU"],"from":u"RTES"},
	{"name":u"culture","codes":["CUL"],"from":u"RTES"},
	{"name":u"économie circulaire","codes":["ECO","DEC"],"from":u"RTES"},
	{"name":u"entrepreneuriat","codes":["ECO"],"from":u"RTES"},
	{"name":u"foncier","codes":["AME"],"from":u"RTES"},
	{"name":u"habitat","codes":["HAB"],"from":u"RTES"},
	{"name":u"immigration","codes":["AUT"],"from":u"RTES"},
	{"name":u"lieux partagés","codes":["COO","AUT"],"from":u"RTES"},
	{"name":u"logement","codes":["HAB"],"from":u"RTES"},
	{"name":u"marchés publics","codes":["FIN"],"from":u"RTES"},
	{"name":u"mobilité durable","codes":["MOB"],"from":u"RTES"},
	{"name":u"numérique","codes":["NUM"],"from":u"RTES"},
	{"name":u"PTCE","codes":["ECO","GOU","COO"],"from":u"RTES"},
	{"name":u"rénovation thermique","codes":["HAB","ENE"],"from":u"RTES"},
	{"name":u"rural","codes":["AUT"],"from":u"RTES"},
	{"name":u"Scic","codes":["ECO","GOU","COO"],"from":u"RTES"},
	{"name":u"transition énergétique","codes":["ENE"],"from":u"RTES"},
	{"name":u"utilité sociale","codes":["COH"],"from":u"RTES"},
	{"name":u"(Biens) communs","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Accessibilité","codes":["COH","INS"],"from":u"Semeoz"},
	{"name":u"Actions citoyennes","codes":["CIT"],"from":u"Semeoz"},
	{"name":u"Agriculture","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Agriculture biologique","codes":["AGR","BIO"],"from":u"Semeoz"},
	{"name":u"Agriculture urbaine","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Agroécologie","codes":["AGR","BIO"],"from":u"Semeoz"},
	{"name":u"Alimentation","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Alternatives","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"AMAP","codes":["AGR","ECO"],"from":u"Semeoz"},
	{"name":u"Apprentissages","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Arts / Culture","codes":["CUL"],"from":u"Semeoz"},
	{"name":u"Associatif / Humanitaire","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Auto-construction","codes":["HAB"],"from":u"Semeoz"},
	{"name":u"Auto-gestion","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Autonomie","codes":["COH"],"from":u"Semeoz"},
	{"name":u"Banque éthique","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Bien-être / Beauté","codes":["SAN"],"from":u"Semeoz"},
	{"name":u"Biodiversité","codes":["BIO"],"from":u"Semeoz"},
	{"name":u"Biodynamie","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Blockchain","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Bonheur","codes":["SAN"],"from":u"Semeoz"},
	{"name":u"Bonheur au travail","codes":["SAN","EMP"],"from":u"Semeoz"},
	{"name":u"Bonheur National Brut","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Budget participatif","codes":["FIN","CIT"],"from":u"Semeoz"},
	{"name":u"Cartographie","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Circuits courts","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Climat","codes":["CLI"],"from":u"Semeoz"},
	{"name":u"Co-création","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Co-production","codes":["COO","ECO"],"from":u"Semeoz"},
	{"name":u"Collapsologie","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Commerce","codes":["COM"],"from":u"Semeoz"},
	{"name":u"Commerce équitable","codes":["COM"],"from":u"Semeoz"},
	{"name":u"CommonsTous2017","codes":["GOU","COO"],"from":u"Semeoz"},
	{"name":u"Communaux collaboratifs","codes":["GOU","COO"],"from":u"Semeoz"},
	{"name":u"Communication / Presse","codes":["COM"],"from":u"Semeoz"},
	{"name":u"Compost","codes":["DEC"],"from":u"Semeoz"},
	{"name":u"Consommaction","codes":["CIT","BIO"],"from":u"Semeoz"},
	{"name":u"Consommation collaborative","codes":["CIT","COO"],"from":u"Semeoz"},
	{"name":u"Consommation responsable","codes":["CIT","COO"],"from":u"Semeoz"},
	{"name":u"Conspirateurs positifs","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Construction écologique","codes":["HAB"],"from":u"Semeoz"},
	{"name":u"Coopérative","codes":["GOU","COO"],"from":u"Semeoz"},
	{"name":u"Copyleft","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Cosmétiques naturels","codes":["SAN"],"from":u"Semeoz"},
	{"name":u"Covoiturage","codes":["MOB"],"from":u"Semeoz"},
	{"name":u"Coworking","codes":["EMP"],"from":u"Semeoz"},
	{"name":u"Créatifs culturels","codes":["CUL"],"from":u"Semeoz"},
	{"name":u"Création participative","codes":["CUL"],"from":u"Semeoz"},
	{"name":u"Crowdfunding (Financement participatif)","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Crowdlending","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Décroissance","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Démocratie directe","codes":["GOU","PAR"],"from":u"Semeoz"},
	{"name":u"Démocratie liquide","codes":["GOU","PAR"],"from":u"Semeoz"},
	{"name":u"Démocratie ouverte (OpenGov)","codes":["GOU","PAR"],"from":u"Semeoz"},
	{"name":u"Démocratie participative","codes":["GOU","PAR"],"from":u"Semeoz"},
	{"name":u"Développement durable","codes":["ECO","COH","BIO"],"from":u"Semeoz"},
	{"name":u"Développement rural","codes":["AME"],"from":u"Semeoz"},
	{"name":u"Do it yourself","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Don","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Droit ouvert (Open Law)","codes":["DRO"],"from":u"Semeoz"},
	{"name":u"Echange","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Eco-conception","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Eco-habitat","codes":["HAB"],"from":u"Semeoz"},
	{"name":u"Ecole alternative","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Ecologie","codes":["BIO","DEC","CLI"],"from":u"Semeoz"},
	{"name":u"Economie circulaire","codes":["ECO","DEC"],"from":u"Semeoz"},
	{"name":u"Economie collaborative","codes":["ECO","COO"],"from":u"Semeoz"},
	{"name":u"Economie contributive","codes":["ECO","COO"],"from":u"Semeoz"},
	{"name":u"Economie de partage","codes":["ECO","COO"],"from":u"Semeoz"},
	{"name":u"Economie ouverte","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Economie positive","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Economie responsable","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Economie sociale","codes":["ECO","COH"],"from":u"Semeoz"},
	{"name":u"Economie solidaire","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Economie verte","codes":["ECO","BIO"],"from":u"Semeoz"},
	{"name":u"Economie / finance","codes":["ECO","FIN"],"from":u"Semeoz"},
	{"name":u"Ecosystème","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Ecotourisme","codes":["TOU"],"from":u"Semeoz"},
	{"name":u"Ecovillage","codes":["HAB","GOU"],"from":u"Semeoz"},
	{"name":u"Ecriture participative","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Education populaire","codes":["EDU","COH"],"from":u"Semeoz"},
	{"name":u"Education positive","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Education / parentalisé","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Energie","codes":["ENE"],"from":u"Semeoz"},
	{"name":u"Energie solaire","codes":["ENE"],"from":u"Semeoz"},
	{"name":u"Energies renouvelables","codes":["ENE"],"from":u"Semeoz"},
	{"name":u"Engagement","codes":["CIT"],"from":u"Semeoz"},
	{"name":u"Entraide","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Entreprenariat","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Entreprenariat social","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Environnement","codes":["BIO"],"from":u"Semeoz"},
	{"name":u"Epargne solidaire","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Epicerie vrac","codes":["ECO","DEC"],"from":u"Semeoz"},
	{"name":u"Espace collaboratif","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Fab Lab","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Faircoin","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Féminisme","codes":["DRO"],"from":u"Semeoz"},
	{"name":u"Finance équitable","codes":["FIN","COH"],"from":u"Semeoz"},
	{"name":u"Finance responsable ","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Finance solidaire","codes":["FIN","COH"],"from":u"Semeoz"},
	{"name":u"Fleur biologique","codes":["BIO"],"from":u"Semeoz"},
	{"name":u"Freegan","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Gouvernance","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Gouvernance collective","codes":["GOU","PAR"],"from":u"Semeoz"},
	{"name":u"Gratuit","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Habitat","codes":["HAB"],"from":u"Semeoz"},
	{"name":u"Habitat léger","codes":["HAB"],"from":u"Semeoz"},
	{"name":u"Habitat partagé","codes":["HAB","COO"],"from":u"Semeoz"},
	{"name":u"Habitat participatif","codes":["HAB","PAR"],"from":u"Semeoz"},
	{"name":u"Holacratie","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Informatique durable","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Initiatives","codes":["CIT"],"from":u"Semeoz"},
	{"name":u"Innovation sociale","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Insertion","codes":["INS"],"from":u"Semeoz"},
	{"name":u"Instruction en famille","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Intérêt général","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Internet libre","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Investissement d'impact","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Investissement d'éthique","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Investissement solidaire","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Jardinage / Bricolage","codes":["AGR","BIO"],"from":u"Semeoz"},
	{"name":u"Jardins partagés","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Jeux / Loisirs","codes":["CUL"],"from":u"Semeoz"},
	{"name":u"Journalisme constructif","codes":["COM"],"from":u"Semeoz"},
	{"name":u"Journalisme participatif","codes":["COM","PAR"],"from":u"Semeoz"},
	{"name":u"Juridique","codes":["DRO"],"from":u"Semeoz"},
	{"name":u"Légumes bio","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Licences libres","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Lien social","codes":["COH"],"from":u"Semeoz"},
	{"name":u"Livre","codes":["CUL"],"from":u"Semeoz"},
	{"name":u"Logiciel libre","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Low Tech","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Makers","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Matériel libre","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Mécénat","codes":["MEC"],"from":u"Semeoz"},
	{"name":u"Médecine / Santé","codes":["SAN"],"from":u"Semeoz"},
	{"name":u"Medialab","codes":["COM"],"from":u"Semeoz"},
	{"name":u"Méthode Montessori","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Micro-crédit","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Microdon","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Microfinance","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"mobilité","codes":["MOB"],"from":u"Semeoz"},
	{"name":u"Mode de vie","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Monnaies alternatives","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Mooc","codes":["EDU","NUM"],"from":u"Semeoz"},
	{"name":u"Musique libre","codes":["CUL"],"from":u"Semeoz"},
	{"name":u"No Poo","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Non violence","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Objets connectés","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Open data","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Open education","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Open Science","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Open-Access","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Open-source","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Optimisme","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Partage","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Pédagogie / Instruction","codes":["EDU"],"from":u"Semeoz"},
	{"name":u"Peer Production Licence","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Peer-to-peer (pair à pair)","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Pensée / Savoirs","codes":["REC"],"from":u"Semeoz"},
	{"name":u"Permaculture","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Produits bio","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Produits locaux","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Recherche collaborative","codes":["REC"],"from":u"Semeoz"},
	{"name":u"Récup","codes":["DEC"],"from":u"Semeoz"},
	{"name":u"Recyclage","codes":["DEC"],"from":u"Semeoz"},
	{"name":u"Repair Café","codes":["DEC"],"from":u"Semeoz"},
	{"name":u"Réseaux sociaux","codes":["COM"],"from":u"Semeoz"},
	{"name":u"Résilience","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Revenu contributif","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Revenu de base","codes":["FIN"],"from":u"Semeoz"},
	{"name":u"Savoir libre","codes":["REC"],"from":u"Semeoz"},
	{"name":u"Sciences collaboratives","codes":["REC"],"from":u"Semeoz"},
	{"name":u"Sciences libres ","codes":["REC"],"from":u"Semeoz"},
	{"name":u"Sciences / Technologies","codes":["REC"],"from":u"Semeoz"},
	{"name":u"Self-management","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Sobriété","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Société civile","codes":["CIT"],"from":u"Semeoz"},
	{"name":u"Sociocratie","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Solidarité","codes":["COH"],"from":u"Semeoz"},
	{"name":u"Solutions","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Supermarché coopératif","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Système d'échange local","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Think Tank","codes":["REC"],"from":u"Semeoz"},
	{"name":u"Tiers lieux","codes":["HAB"],"from":u"Semeoz"},
	{"name":u"Tirage au sort","codes":["GOU"],"from":u"Semeoz"},
	{"name":u"Tourisme équitable","codes":["TOU"],"from":u"Semeoz"},
	{"name":u"Tourisme solidaire","codes":["TOU"],"from":u"Semeoz"},
	{"name":u"Transition","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Transition écologique","codes":["BIO","CLI","ENE"],"from":u"Semeoz"},
	{"name":u"Transition économique","codes":["ECO"],"from":u"Semeoz"},
	{"name":u"Transition énergétique","codes":["ENE"],"from":u"Semeoz"},
	{"name":u"Transition sociale","codes":["COH"],"from":u"Semeoz"},
	{"name":u"Transports","codes":["MOB"],"from":u"Semeoz"},
	{"name":u"Transports doux","codes":["MOB"],"from":u"Semeoz"},
	{"name":u"Travail collaboratif","codes":["EMP","COO"],"from":u"Semeoz"},
	{"name":u"Troc","codes":["COO"],"from":u"Semeoz"},
	{"name":u"Urbanisme","codes":["AME"],"from":u"Semeoz"},
	{"name":u"Urbanisme participatif","codes":["AME","PAR"],"from":u"Semeoz"},
	{"name":u"Vacances / Voyages","codes":["CUL"],"from":u"Semeoz"},
	{"name":u"Veganisme","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Végétalisme","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Végétarisme","codes":["AGR"],"from":u"Semeoz"},
	{"name":u"Vie de quartier","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Vie pratique","codes":["AUT"],"from":u"Semeoz"},
	{"name":u"Vie sociale","codes":["COH"],"from":u"Semeoz"},
	{"name":u"Web sémantique","codes":["NUM"],"from":u"Semeoz"},
	{"name":u"Wiki","codes":["NUM","COO"],"from":u"Semeoz"},
	{"name":u"Zéro déchet","codes":["DEC"],"from":u"Semeoz"},
	{"name":u"Activités à la maison, Auto-production, Travail domestique","codes":["ECO","AUT"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Activités professionnelles, scientifiques et techniques","codes":["EMP","AUT"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Activités sociales, Réparations, Bien-être","codes":["COH"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Administration et management, tourisme et location","codes":["TOU","GOU"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Administration publique et sécurité sociale","codes":["SAN","COH"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Agriculture et environnement","codes":["AGR","BIO"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Art, culture, loisirs et sports","codes":["CUL","LOI","SPO"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Artisanat et manifacturier","codes":["ECO"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Commerce et distribution","codes":["COM"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Construction, travaux publics et rénovation","codes":["HAB"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Diplomatie internationale et Coopération","codes":["GOU","COO"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Éducation et formation","codes":["EDU","FOR"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Finance, assurance et activités connexes","codes":["FIN"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Habitat et logement","codes":["HAB"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Information, communication et technologies","codes":["COM","NUM"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Mines et carrières","codes":["ECO"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Production et distribution de l'énergie","codes":["ENE","ECO"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Recyclage, traitement des déchets, cycle de l'eau et la restauration écologique","codes":["DEC","EAU","BIO"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Restauration, hôtellerie, catering","codes":["TOU"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Services sociaux et santé","codes":["COH","SAN"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Transport, logistique et entreposage","codes":["MOB"],"from":u"Socioéco / Carte ESS global"},
	{"name":u"Vivre ensemble","codes":["COH"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Vivre ensemble","codes":["COH"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Vivre ensemble","codes":["COH","DRO"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Besoins essentiels","codes":["AGR","SAN","HAB","EDU"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Besoins essentiels","codes":["AGR","SAN","HAB"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Besoins essentiels","codes":["AGR","SAN","HAB","DRO"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Inclusion sociale","codes":["COH","INS"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Inclusion sociale","codes":["COH"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Inclusion sociale","codes":["COH"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Santé","codes":["SAN"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Santé","codes":["SAN"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Santé","codes":["SAN"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Culture et savoirs","codes":["CUL","FOR"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Culture et savoirs","codes":["CUL"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Culture et savoirs","codes":["CUL","FOR"],"from":u"Fondation Cognacq Jay"},
	{"name":u"Bâtiment durable","codes":["HAB"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u"Démarches participatives","codes":["PAR"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u"Energie","codes":["ENE"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u"Environnement","codes":["BIO"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u"Gouvernance","codes":["GOU"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u"Mobilite","codes":["MOB"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u"Urbanisme","codes":["URB"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u"Social - Santé","codes":["SAN","COH"],"from":u"Synergies, réseau de collectivités 53 (Mayenne)"},
	{"name":u" Développement économique - Tourisme","codes":["ECO","TOU"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Environnement - Energie - Transports","codes":["BIO","ENE","MOB"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Culture - Sports - Loisirs","codes":["CUL","LOI","SPO"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Habitat - Urbanisme - Paysage","codes":["HAB"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Organisation territoriale - Elus","codes":["GOU"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Numérique - Communication","codes":["COM","NUM"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Finances - Commande publique","codes":["FIN","COP"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Citoyenneté - Associations - Jeunesse","codes":["CIT","COH","JEU"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Education - Enseignement Supérieur","codes":["EDU"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u" Emploi - Formation","codes":["EMP","FOR"],"from":u"Territoires Conseils (ex Mairie Conseils)"},
	{"name":u"accès à l’énergie","codes":["COH","ENE"],"from":u"UNCCAS"},
	{"name":u"accès aux loisirs","codes":["COH","LOI"],"from":u"UNCCAS"},
	{"name":u"accès aux soins","codes":["COH","SAN"],"from":u"UNCCAS"},
	{"name":u"accès aux transports","codes":["COH","MOB"],"from":u"UNCCAS"},
	{"name":u"accompagnement","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"accompagnement social au logement","codes":["COH","HAB"],"from":u"UNCCAS"},
	{"name":u"accueil de jour","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"accueil parents enfants","codes":["SER","JEU"],"from":u"UNCCAS"},
	{"name":u"accueil temporaire","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"action d’éducation","codes":["EDU"],"from":u"UNCCAS"},
	{"name":u"activité d’animation","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"activité de prévention","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"adaptation à la perte d’autonomie de l’occupant","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"aide à la mobilité et transport","codes":["SER","MOB"],"from":u"UNCCAS"},
	{"name":u"aide à la parentalité","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"aide alimentaire","codes":["SER","AGR"],"from":u"UNCCAS"},
	{"name":u"aide aux aidants","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"aide et activités à domicile","codes":["COH","SER"],"from":u"UNCCAS"},
	{"name":u"aide juridique","codes":["DRO"],"from":u"UNCCAS"},
	{"name":u"allocation logement temporaire","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"alzheimer","codes":["SAN"],"from":u"UNCCAS"},
	{"name":u"amélioration de la qualité","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"aménagement de l’habitat","codes":["HAB","AME"],"from":u"UNCCAS"},
	{"name":u"aménagement durable","codes":["AME"],"from":u"UNCCAS"},
	{"name":u"analyse des besoins sociaux","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"animation et convivialité","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"auto-réhabilitation","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"certification","codes":["AUT"],"from":u"UNCCAS"},
	{"name":u"chantier d’insertion","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"chèque d’accompagnement personnalisé","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"CHRS","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"CLIC","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"communication","codes":["COM"],"from":u"UNCCAS"},
	{"name":u"coordination des aides","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"coordination et organisation du service","codes":["GOU"],"from":u"UNCCAS"},
	{"name":u"crèches","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"dépendance","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"développement durable","codes":["COH","BIO","ECO"],"from":u"UNCCAS"},
	{"name":u"domiciliation","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"économie durable et solidaire","codes":["ECO"],"from":u"UNCCAS"},
	{"name":u"économies d’énergie","codes":["ENE"],"from":u"UNCCAS"},
	{"name":u"éducation nutritionnelle","codes":["EDU","AGR"],"from":u"UNCCAS"},
	{"name":u"enfance","codes":["JEU"],"from":u"UNCCAS"},
	{"name":u"établissement et service social et médico-social","codes":["COH","SAN"],"from":u"UNCCAS"},
	{"name":u"étude / diagnostic / évaluation","codes":["EVA"],"from":u"UNCCAS"},
	{"name":u"évaluation","codes":["EVA"],"from":u"UNCCAS"},
	{"name":u"exclusions financières","codes":["FIN"],"from":u"UNCCAS"},
	{"name":u"expulsion","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"famille","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"foyer de jeunes travailleurs","codes":["HAB","JEU"],"from":u"UNCCAS"},
	{"name":u"foyer logement","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"garde et téléassistance","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"groupement de coopération sociale et médico-sociale","codes":["COH","SAN"],"from":u"UNCCAS"},
	{"name":u"habitat","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"halte-garderie","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"hébergement d’urgence","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"insertion","codes":["INS"],"from":u"UNCCAS"},
	{"name":u"insertion par l’activité économique","codes":["EMP","INS"],"from":u"UNCCAS"},
	{"name":u"insertion par l’emploi","codes":["EMP","INS"],"from":u"UNCCAS"},
	{"name":u"insertion par la culture","codes":["INS","CUL"],"from":u"UNCCAS"},
	{"name":u"insertion par le sport","codes":["INS","SPO"],"from":u"UNCCAS"},
	{"name":u"intercommunalité","codes":["GOU","AUT"],"from":u"UNCCAS"},
	{"name":u"intergénérations","codes":["SEN"],"from":u"UNCCAS"},
	{"name":u"isolement","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"jeunesse","codes":["JEU"],"from":u"UNCCAS"},
	{"name":u"logement","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"logement social","codes":["COH","HAB"],"from":u"UNCCAS"},
	{"name":u"lutte contre le non-recours","codes":["DRO","SER"],"from":u"UNCCAS"},
	{"name":u"lutte contre les exclusions","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"maltraitance","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"médiation familiale","codes":["MED"],"from":u"UNCCAS"},
	{"name":u"médiation locative","codes":["MED","HAB"],"from":u"UNCCAS"},
	{"name":u"mesure de protection","codes":["DRO"],"from":u"UNCCAS"},
	{"name":u"microcrédit","codes":["FIN"],"from":u"UNCCAS"},
	{"name":u"observation des territoires et des publics","codes":["COH","AUT"],"from":u"UNCCAS"},
	{"name":u"organisation de manifestations et d’évènements","codes":["AUT"],"from":u"UNCCAS"},
	{"name":u"organisation du CCAS","codes":["GOU"],"from":u"UNCCAS"},
	{"name":u"participation des usagers","codes":["PAR"],"from":u"UNCCAS"},
	{"name":u"personnes âgées","codes":["SEN"],"from":u"UNCCAS"},
	{"name":u"personnes handicapées","codes":["HAN"],"from":u"UNCCAS"},
	{"name":u"petits travaux et entretien de la maison","codes":["HAB"],"from":u"UNCCAS"},
	{"name":u"plate-forme de services","codes":["COH","SER"],"from":u"UNCCAS"},
	{"name":u"point information famille","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"pôles d’accueil en réseau pour l’accès aux droits sociaux  (PARADS)","codes":["DRO"],"from":u"UNCCAS"},
	{"name":u"politique de la ville","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"prévention canicule","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"prévention coupures","codes":["SER"],"from":u"UNCCAS"},
	{"name":u"prévention santé","codes":["SAN"],"from":u"UNCCAS"},
	{"name":u"programmes/financements européens","codes":["AUT"],"from":u"UNCCAS"},
	{"name":u"REAAP","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"relais assistantes maternelles","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"repas et restauration","codes":["AGR"],"from":u"UNCCAS"},
	{"name":u"restauration de l’image de soi","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"santé","codes":["SAN"],"from":u"UNCCAS"},
	{"name":u"santé mentale","codes":["SAN"],"from":u"UNCCAS"},
	{"name":u"semaine bleue","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"services aux familles","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"structure d’accueil de la petite enfance","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"technologies de l’information et de la communication","codes":["COM","NUM"],"from":u"UNCCAS"},
	{"name":u"urgence sociale","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"vacances","codes":["LOI"],"from":u"UNCCAS"},
	{"name":u"veille sociale","codes":["COH"],"from":u"UNCCAS"},
	{"name":u"Achats durables","codes":["COP"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Culture et tourisme","codes":["CUL","TOU"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Démarche globale","codes":["GOU"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Déplacement ","codes":["MOB"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Eau et assainissement","codes":["EAU"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Economie locale, actions sociales","codes":["COH","ECO"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Energie","codes":["ENE"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Engagements","codes":["CIT"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Equipement public","codes":["AUT"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Espaces publics","codes":["AME","URB"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Espaces verts et biodiversité","codes":["BIO"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Quartiers d'habitation et renouvellement","codes":["HAB","AME","URB"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"Restauration collective","codes":["AGR"],"from":u"Bruded - réseau breton collectivités DD"},
	{"name":u"AGIR POUR LA BIODIVERSITE","codes":["BIO"],"from":u"cerdd"},
	{"name":u"ALIMENTATION DURABLE","codes":["AGR"],"from":u"cerdd"},
	{"name":u"CHANGEMENT CLIMATIQUE","codes":["CLI"],"from":u"cerdd"},
	{"name":u"TERRITOIRES DURABLES","codes":["COH","ECO","BIO"],"from":u"cerdd"},
	{"name":u"TRANSITIONS ECONOMIQUES","codes":["ECO"],"from":u"cerdd"},
	{"name":u"URBANISME ET PLANIFICATION DURABLES","codes":["URB","AME"],"from":u"cerdd"},
	{"name":u"L'Européen d'à côté","codes":["AUT"],"from":u"Europe en France"},
	{"name":u"Agriculture","codes":["AGR"],"from":u"Europe en France"},
	{"name":u"Agriculture et pêche","codes":["AGR","AGR"],"from":u"Europe en France"},
	{"name":u"Aides aux entreprises","codes":["ECO"],"from":u"Europe en France"},
	{"name":u"Attractivité du territoire","codes":["AUT","ECO"],"from":u"Europe en France"},
	{"name":u"Coopération","codes":["GOU","COO"],"from":u"Europe en France"},
	{"name":u"Culture","codes":["CUL"],"from":u"Europe en France"},
	{"name":u"Culture et tourisme","codes":["CUL","TOU"],"from":u"Europe en France"},
	{"name":u"Développement durable","codes":["ECO","BIO","COH"],"from":u"Europe en France"},
	{"name":u"Développement durable et environnement","codes":["BIO"],"from":u"Europe en France"},
	{"name":u"Développement local et cohésion territoriale","codes":["COH","AME","URB"],"from":u"Europe en France"},
	{"name":u"Développement rural","codes":["AME","ECO","URB"],"from":u"Europe en France"},
	{"name":u"Développement urbain","codes":["AME","ECO","URB"],"from":u"Europe en France"},
	{"name":u"Eco-tourisme","codes":["TOU","BIO"],"from":u"Europe en France"},
	{"name":u"Emploi et inclusion sociale","codes":["EMP","COH"],"from":u"Europe en France"},
	{"name":u"Energie","codes":["ENE"],"from":u"Europe en France"},
	{"name":u"Environnement","codes":["BIO"],"from":u"Europe en France"},
	{"name":u"Espaces naturels à enjeux","codes":["BIO"],"from":u"Europe en France"},
	{"name":u"Formation","codes":["FOR"],"from":u"Europe en France"},
	{"name":u"Institutions","codes":["GOU"],"from":u"Europe en France"},
	{"name":u"Les grands projets européens 2007-2013","codes":["AUT"],"from":u"Europe en France"},
	{"name":u"Prévention des risques","codes":["CLI"],"from":u"Europe en France"},
	{"name":u"Recherche et Innovation","codes":["REC"],"from":u"Europe en France"},
	{"name":u"Santé","codes":["SAN"],"from":u"Europe en France"},
	{"name":u"Services au public","codes":["SER"],"from":u"Europe en France"},
	{"name":u"TIC","codes":["COM","NUM"],"from":u"Europe en France"},
	{"name":u"Tourisme","codes":["TOU"],"from":u"Europe en France"},
	{"name":u"Transports","codes":["MOB"],"from":u"Europe en France"},
	{"name":u"Urbain","codes":["AUT"],"from":u"Europe en France"},
	{"name":u"Inclusion sociale","codes":["COH","INS","EMP"],"from":u"Europe en France V2"},
	{"name":u"Innovation","codes":["NUM","REC","AUT"],"from":u"Europe en France V2"},
	{"name":u"Protection de l'environnement","codes":["CLI","BIO","ENE"],"from":u"Europe en France V2"},
	{"name":u"Energies renouvelables","codes":["ENE"],"from":u"Europe en France V2"},
	{"name":u"Emploi  ","codes":["EMP","INS","FOR"],"from":u"Europe en France V2"},
	{"name":u"Développement régional","codes":["AME","ECO","URB"],"from":u"Europe en France V2"},
	{"name":u"Egalité femmes-hommes","codes":["DRO"],"from":u"Europe en France V2"},
	{"name":u"Elections européennes","codes":["CIT","PAR","GOU"],"from":u"Europe en France V2"},
	{"name":u"Recherche   ","codes":["REC"],"from":u"Europe en France V2"},
	{"name":u"Sylviculture","codes":["AGR","BIO","AME"],"from":u"Europe en France V2"},
	{"name":u"TIC, numérique","codes":["NUM"],"from":u"Europe en France V2"},
	{"name":u"Transition énergétique","codes":["ENE","CLI","HAB"],"from":u"Europe en France V2"},
	{"name":u"Transports","codes":["MOB","SER","AME"],"from":u"Europe en France V2"},
	{"name":u"Agriculture","codes":["AGR"],"from":u"Europe en France V2"},
	{"name":u"Alimentation","codes":["AGR"],"from":u"Europe en France V2"},
	{"name":u"Aménagement du territoire et cadre de vie","codes":["AME","SER"],"from":u"Europe en France V2"},
	{"name":u"Développement urbain","codes":["URB","AME","ECO"],"from":u"Europe en France V2"},
	{"name":u"Infrastructures locales","codes":["AME","SER"],"from":u"Europe en France V2"},
	{"name":u"Patrimoine","codes":["CUL"],"from":u"Europe en France V2"},
	{"name":u"Santé","codes":["SAN"],"from":u"Europe en France V2"},
	{"name":u"Développement rural","codes":["AME","AGR","ECO"],"from":u"Europe en France V2"},
	{"name":u"Culture","codes":["CUL"],"from":u"Europe en France V2"},
	{"name":u"Services au public","codes":["SER"],"from":u"Europe en France V2"},
	{"name":u"Sport","codes":["SPO"],"from":u"Europe en France V2"},
	{"name":u"Développement durable","codes":["BIO","ECO","COH"],"from":u"Europe en France V2"},
	{"name":u"Développement économique","codes":["ECO"],"from":u"Europe en France V2"},
	{"name":u"Tourisme","codes":["TOU"],"from":u"Europe en France V2"},
	{"name":u"Entreprises en difficulté","codes":["FIN","ECO"],"from":u"Europe en France V2"},
	{"name":u"Economie sociale et solidaire","codes":["ECO","INS","COH"],"from":u"Europe en France V2"},
	{"name":u"Activité économique nouvelle","codes":["NUM","ECO"],"from":u"Europe en France V2"},
	{"name":u"Aide aux PME","codes":["ECO","FIN"],"from":u"Europe en France V2"},
	{"name":u"Changement climatique","codes":["CLI"],"from":u"Europe en France V2"},
	{"name":u"Coopération","codes":["COO"],"from":u"Europe en France V2"},
	{"name":u"Tranfrontalier (hors programme de CTE)","codes":["GOU"],"from":u"Europe en France V2"},
	{"name":u"Stratégies macro-régionales","codes":["AME","GOU","AUT"],"from":u"Europe en France V2"},
	{"name":u"Coopération territoriale européenne","codes":["AME","GOU"],"from":u"Europe en France V2"},
	{"name":u"Affaires maritimes, pêche, aquaculture","codes":["AGR","EAU","BIO"],"from":u"Europe en France V2"},
	{"name":u"Collectif citoyen & mise en réseau","codes":["CIT","GOU","COO"],"from":u"GNIAC"},
	{"name":u"Communauté d'internautes","codes":["GOU","COO"],"from":u"GNIAC"},
	{"name":u"Conseil","codes":["SER"],"from":u"GNIAC"},
	{"name":u"Echange de services","codes":["SER"],"from":u"GNIAC"},
	{"name":u"Entreprises solidaires","codes":["ECO"],"from":u"GNIAC"},
	{"name":u"Expertise pratique collaborative","codes":["AUT"],"from":u"GNIAC"},
	{"name":u"Finance participative","codes":["FIN"],"from":u"GNIAC"},
	{"name":u"Lien social dans les quartiers","codes":["COH"],"from":u"GNIAC"},
	{"name":u"Logement, santé, éducation, environnement","codes":["HAB","SAN","EDU"],"from":u"GNIAC"},
	{"name":u"Plateforme fédératrice d'entreprises","codes":["ECO","GOU","COO"],"from":u"GNIAC"},
	{"name":u"Plateformes web","codes":["NUM"],"from":u"GNIAC"},
	{"name":u"Promoteur d'initiatives","codes":["AUT"],"from":u"GNIAC"},
	{"name":u"Réseaux","codes":["GOU","COO"],"from":u"GNIAC"},
	{"name":u"Soutien création d'entreprise","codes":["ECO"],"from":u"GNIAC"},
	{"name":u"Soutien recherche d'emploi","codes":["EMP"],"from":u"GNIAC"},
	{"name":u"Think Tank / Do Tank","codes":["AUT"],"from":u"GNIAC"},
	# {"name":u"Pas de catégories thématiques","codes":[""],"from":u"La part du colibri"},

]
normalization_as_json( "NORMALIZATION_TAGS_SOURCES_CIS", NORMALIZATION_TAGS_SOURCES_CIS )







NORMALIZATION_TAGS_SOURCES_CIS_DICT = { k : [] for k in NOMENCLATURE_CIS_DICT.keys() }
for tag in NORMALIZATION_TAGS_SOURCES_CIS : 
	# print tag
	for code in tag["codes"] :
		if tag["name"] not in NORMALIZATION_TAGS_SOURCES_CIS_DICT[code] :
			NORMALIZATION_TAGS_SOURCES_CIS_DICT[code].append(tag["name"])

for k,v in NORMALIZATION_TAGS_SOURCES_CIS_DICT.iteritems() : 
	v.sort()

normalization_as_json( "NORMALIZATION_TAGS_SOURCES_CIS_DICT", NORMALIZATION_TAGS_SOURCES_CIS_DICT )

# from 	pprint import pprint, pformat
# pprint(NORMALIZATION_TAGS_SOURCES_CIS_DICT)
